#!/bin/bash

function usage() {
  echo "usage: wrk.sh -bd <site>"
  echo "-b - build site with ./sites/<site> template in ./www/<site>"
  echo "-d - deploy site from ./www/<site>/*"
}

while getopts "bd" flag; do
  case "${flag}" in
    b) BUILD=1 ;;
    d) DEPLOY=1 ;;
  esac
done
shift $((OPTIND - 1))
TMP_NAME=$1 # template name

BUILD_CONFIG="sites/${TMP_NAME}/build.json"

if [ -e $BUILD_CONFIG ]; then
  SSH_SERVER=$(jq -r '.remote.ssh' $BUILD_CONFIG)
  SSH_PATH=$(jq -r '.remote.path' $BUILD_CONFIG)
else
    echo "No template build config file"
    exit 1
fi

echo "build: $BUILD deploy: $DEPLOY "
echo "ssh: $SSH_SERVER path: $SSH_PATH "

if [ "$BUILD" = "1" ]; then
  node --import=tsx ./src/build.ts $TMP_NAME
fi

if [ "$DEPLOY" = "1" ]; then
  echo "rm -r ${SSH_PATH}*"
  ssh memd -t "rm -r ${SSH_PATH}*"
  scp -rp ./www/$TMP_NAME/* $SSH_SERVER:$SSH_PATH
fi
