#!/bin/bash

function usage() {
  echo "usage: wrk.sh -bd <site>"
  echo " -h - help description"
  echo " -b - build site with ./sites/<site> template in ./www/<site>"
  echo " -d - deploy site from ./www/<site>/*"
  echo " -c - copy default site template in new location ./sites/default =>  ./sites/<site>"
  echo " -k - clear console with 'clear'"
  echo " -----------------"
  echo " -D - dev mode"
  echo " -C - clear build dir: dev ? 'rm -r dirPath/*'  : 'rm -r dirPath'"
  echo " -S - build styles (SCSS files)"
  echo " -J - build js (TS files)"
  echo " -H - build html (PUG files)"
  echo " -----------------"
  echo "'./wrk -b <site>' === './wrk -bCSJH <site>'"
  echo "'./wrk -bd <site>' === './wrk -bdCSJH <site>'"
  echo "'./wrk -bD <site>' === './wrk -bDCSJH <site>'"
  echo "'./wrk -bdD <site>' === './wrk -bdDCSJH <site>'"
  echo "'./wrk -bDS <site>' rebuild styles only"
  echo "'./wrk -bDH <site>' rebuild html only"
  echo "'./wrk -bDJ <site>' rebuild js only"
  exit 1
}

BUILD_OPTS=""

while getopts "hbdcDCSJHk" flag; do
  case "${flag}" in
    b) BUILD=1 ;;
    d) DEPLOY=1 ;;
    c) COPY=1 ;;
    h) HELP=1 ;;
    # build helpers
    D) BUILD_OPTS="${BUILD_OPTS}D" ;; # dev mode
    C) BUILD_OPTS="${BUILD_OPTS}C" ;; # clear build dir: dev ? 'rm -r dirPath/*'  : 'rm -r dirPath'
    S) BUILD_OPTS="${BUILD_OPTS}S" ;; # build styles (SCSS files)
    J) BUILD_OPTS="${BUILD_OPTS}J" ;; # build js (TS files)
    H) BUILD_OPTS="${BUILD_OPTS}H" ;; # build html (PUG files)
    k) CLEAR_CONSOLE=1 ;;
  esac
done
shift $((OPTIND - 1))
TMP_NAME=$1 # template name
TMP_DIR="sites/${TMP_NAME}"
DEPLOY_CONFIG="${TMP_DIR}/deploy.json"
BUILD_DIR="www/$TMP_NAME"

# -k ----
if [ "$CLEAR_CONSOLE" = "1" ]; then
    clear
fi
# -h ----
if [ "$HELP" = "1" ]; then
    usage
fi
# -c ----
if [ "$COPY" = "1" ]; then
  if [ -d "$TMP_DIR" ]; then
    echo "Directory  '$TMP_NAME'   does exist."
  else
    cp -R sites/default $TMP_DIR
  fi
fi

if [ -e $DEPLOY_CONFIG ]; then
  SSH_SERVER=$(jq -r '.remote.ssh' $DEPLOY_CONFIG)
  SSH_PATH=$(jq -r '.remote.path' $DEPLOY_CONFIG)
else
    echo "No template build config file"
    exit 1
fi

echo "copy: $COPY  build: $BUILD  deploy: $DEPLOY"
echo "ssh: $SSH_SERVER path: $SSH_PATH "

# -b ---- build
if [ "$BUILD" = "1" ]; then
  node --import=tsx ./src/build.ts $TMP_NAME $BUILD_OPTS
fi

# -- deploy
if [ "$DEPLOY" = "1" ]; then
  echo "rm -r ${SSH_PATH}*"
  ssh memd -t "rm -r ${SSH_PATH}*"
  scp -rp $BUILD_DIR/* $SSH_SERVER:$SSH_PATH
fi
