#!/bin/bash

source ./actions/-head -N copy $@

TMPL_NAME=$PRM1 # template name

TMPL_DIR="sites/${TMPL_NAME}"

if [ -d "$TMPL_DIR" ]; then
  ./actions/-error "Directory  '$TMPL_NAME'   does exist. Enter other site template name"
  ./actions/-see-help copy
else
  echo "Print 'y' to create '$TMPL_NAME' site template from default"
  read ACCEPT
  echo "$ACCEPT"
  if [ "$ACCEPT" = "y" ] || [ "$ACCEPT" = "Y" ]; then
    cp -R sites/default $TMPL_DIR
    cd $TMPL_DIR
    git init
    cd ..
    ls -lt
  fi
fi

