#!/bin/bash

source ./actions/-head -N "doc"  -T "Convert manuals" $@

ACTION=$PRM1

TEXTS=("man" "wrk" "copy" "srv" "new" "vars" "doc")
PARTS=("man" "wrk" "copy" "srv" "new" "vars")

function doText() {
  for NM in "${TEXTS[@]}"; do
    pandoc docs/yarn/$NM.md -t plain -o src/help/yarn-$NM.txt
  done
}
function doPage() {
  LIST=""
  for NM in "${PARTS[@]}"; do
    LIST="$LIST docs/yarn/$NM.md"
  done
  cat docs/docs-manual-vars.md $LIST  > sites/default/pages/docs/manual/index.en.md
}

if [ "$ACTION" = "text" ]; then
  doText
elif [ "$ACTION" = "page" ]; then
  doPage
elif [ "$ACTION" = "" ]; then
  echo "Create all manuals and "
  doText
  doPage
else
  echo "unknown parameter: $1"
  echo "yarn doc -h"
fi
