#!/bin/bash

source ./actions/-head -N "man" -T "Command list"  $@

CMD=$PRM1

if [ "$CMD" = "" ]; then
echo "- yarn fmt"
echo "- yarn fmt:check"
echo "- yarn man"
echo "- yarn copy <new-site-name>"
echo "- yarn new -c <site> <path:lang>"
echo "- yarn vars -c <site> <path:lang> <list>"
echo "- yarn srv -c -D -p <port> <site>"
echo "- yarn wrk -b -d -DCSJHI <site>"
echo "- yarn doc"
echo "- yarn logo"
elif [ -f "actions/$CMD" ]; then
  actions/$CMD -ch
else
  echo "Unknown command: $CMD"

fi
