#!/bin/bash

source ./actions/-head -N "man"  $@

CMD=$PRM1

if [ "$CMD" = "" ]; then
echo ""
echo "- yarn fmt"
echo "- yarn fmt:site <site>"
echo "- yarn fmt:check"
echo "- yarn man <cmd>"
echo "- yarn copy <new-site-name>"
echo "- yarn new -c <site> <path:lang>"
echo "- yarn vars -c <site> <path:lang> <list>"
echo "- yarn srv -c -D -p <port> <site>"
echo "- yarn wrk -b -d -DCSJHI <site>"
echo "- yarn doc"
echo "- yarn logo"
elif [ -f "src/help/yarn-${CMD}.txt" ]; then
  actions/-help $CMD
else
  ./actions/-error "Unknown command: $CMD"
  ./actions/-see-help man
fi
