#!/bin/bash
# -- actions

if [ "$TMPL_NAME" = "" ]; then
  ./actions/-error "No <site> name."
  ./actions/-see-help wrk
  exit 0
fi

if [ ! -d "$TMPL_DIR" ]; then
  ./actions/-error "Directory  '$TMPL_NAME'   does not exist. Check ./sites/"
  ./actions/-see-help wrk
  exit 0
fi

if [ "$BUILD" != "1" ] && [ "$DEPLOY" != "1" ]; then
  ./actions/-error "Select one of working options '-b' or '-d' or both"
  ./actions/-see-help wrk
    exit 0
fi

VR="ACTIONS: "

if [[ "$TMPL_NAME" ]]; then
  VR="$VR <site>: $TMPL_NAME"
fi

if [[ "$DEV" ]]; then
  VR="$VR &dev'"
fi

if [[ "$BUILD" ]]; then
  VR="$VR &build"
fi

if [[ "$DEPLOY" ]]; then
  VR="$VR &deploy"
fi

if [[ "$SERVER" ]]; then
  VR="$VR &server"
fi

if [[ "$COPY_TMP" ]]; then
  VR="$VR &copy-tmp"
fi
if [[ "$ADD_PAGE" ]]; then
  VR="$VR &add-page"
fi
if [[ "$VARS" ]]; then
  VR="$VR &vars"
fi

echo $VR
echo "--------"
echo ""
